
       name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mostrar estructura del proyecto (debug)
        run: |
          echo "Estructura del proyecto:"
          ls -R

      - name: Instalar Node.js (requerido por Railway CLI)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Login en Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: echo $RAILWAY_TOKEN | railway login --ci

      - name: Deploy a Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          railway up --service shimmering-peace
