name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify files
        run: |
          echo "Estructura del proyecto:"
          ls -R
          echo ""
          echo "Contenido de requeriments.txt:"
          cat backend/requirements.txt

      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway login --token $RAILWAY_TOKEN

      - name: Deploy
        run: railway up --detach
