name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Verifica la estructura del proyecto
      - name: Checkout code and verify structure
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Para ver todos los archivos
        
      - name: Debug - Show project structure
        run: |
          echo "Estructura del proyecto:"
          ls -R
          echo ""
          echo "Contenido de backend/requirements.txt:"
          cat backend/requirements.txt || echo "No se encontró requirements.txt"

      # 2. Configura Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Instala Railway CLI
      - name: Install Railway CLI
        run: npm install -g @railway/cli@latest

      # 4. Autenticación con Railway
      - name: Login to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          mkdir -p ~/.railway
          echo "token: $RAILWAY_TOKEN" > ~/.railway/config.yml

      # 5. Despliegue
      - name: Deploy to Railway
        run: railway up --docker --detach
